name = "GeoFormatTypes"
uuid = "68eda718-8dee-11e9-39e7-89f7f65f511f"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.2.1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
